### ISSUE TITLE
Can't configure a second NIC

### ISSUE THREAD

**Issue by Thumpermat** [konstruktoid/hardening-geniso#4]
Hi,

I created a VM with the new vagrant box and cloned it. Then I added a second NIC to the clone, but when I want to configure it, I can't find the correct /etc/netplan configuration file.

Any idea on how to add a second NIC to this VM?

**Comment by Thumpermat** [comment]
Hi,

I managed to created a second NIC using netplan. If you want I can send you my configuration. Otherwise I close the issue

**Comment by konstruktoid** [comment]
Great! I was about to start testing tomorrow, but feel free to include the configuration in this issue before closing. Thanks for sharing.

**Comment by Thumpermat** [comment]
OK. It may not be the most correct way of doing this, but I replaced the `etc/netplan/00-installer-config.yaml` as per attached version and it works.

[00-installer-config.yaml.txt](https://github.com/konstruktoid/hardening-geniso/files/7490894/00-installer-config.yaml.txt)

P.S.: I had to put the`.txt` at the end of the attachment, otherwise I wasn't able to upload it.

**Comment by konstruktoid** [comment]
Thanks!
